services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    userns_mode: host
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      - LAN_SUBNET
      - TRUSTED_WIFI_SUBNET
      - WG_SUBNET
      - IPV6_LAN_SUBNET
      - IPV6_TRUSTED_WIFI_SUBNET
      - IPV6_WG_SUBNET
    command:
      # HTTP Entrypoint
      - "--entrypoints.http.forwardedHeaders.trustedIPs=${LAN_SUBNET},${TRUSTED_WIFI_SUBNET},${WG_SUBNET},172.17.0.0/16,${IPV6_LAN_SUBNET},${IPV6_TRUSTED_WIFI_SUBNET},${IPV6_WG_SUBNET}"
      - "--entrypoints.http.proxyProtocol.trustedIPs=${LAN_SUBNET},${TRUSTED_WIFI_SUBNET},${WG_SUBNET},172.17.0.0/16,${IPV6_LAN_SUBNET},${IPV6_TRUSTED_WIFI_SUBNET},${IPV6_WG_SUBNET}"
      # HTTPS Entrypoint
      - "--entrypoints.https.forwardedHeaders.trustedIPs=${LAN_SUBNET},${TRUSTED_WIFI_SUBNET},${WG_SUBNET},172.17.0.0/16,${IPV6_LAN_SUBNET},${IPV6_TRUSTED_WIFI_SUBNET},${IPV6_WG_SUBNET}"
      - "--entrypoints.https.proxyProtocol.trustedIPs=${LAN_SUBNET},${TRUSTED_WIFI_SUBNET},${WG_SUBNET},172.17.0.0/16,${IPV6_LAN_SUBNET},${IPV6_TRUSTED_WIFI_SUBNET},${IPV6_WG_SUBNET}"
    labels:
      - "checkmk_monitor=true"
      - "traefik.enable=true"

networks:
  traefik_proxy:
    external: true
